baseURL = "/"
languageCode = "en-us"
title = "Where everybody knows my name"
theme = "blackburn"
author = "Norman Bauer"
paginate = 10
relativeURLs = "true"



[params]
  subtitle = "Norm's place for rants and oddball stuff."
  brand = "Norman Bauer"

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Media"
    pre = "<i class='fa fa-newspaper fa-fw'></i>"
    weight = 3
    identifier = "media"
    url = "/media/"
[[menu.main]]
    name = "M2 Money Stock"
    pre = "<i class='fa fa-dollar-sign fa-fw'></i>"
    weight = 4
    identifier = "m2"
    url = "/m2/"
[[menu.main]]
    name = "Interwebs"
    pre = "<i class='fa fa-link fa-fw'></i>"
    weight = 5
    identifier = "links"
    url = "/links/"
[social]

  github = "simulacra10"
  telegram = "simulacra10"
  twitter = "wyeoakmobiledr"
  keybase = "wyeoak"

[og]

    ogfirstname = "Norman"
    oglastname = "Bauer"
    ogusername = "simulacra10"
    oggender = "male"