baseURL = "https://normanbauer.io/"
languageCode = "en-us"
title = "Where everybody knows my name"
theme = "blackburn"
author = "Norman Bauer"
paginate = 10



[params]
  subtitle = "Norm's place for rants and oddball stuff."
  brand = "Norman Bauer"

[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Media"
    pre = "<i class='fa fa-newspaper fa-fw'></i>"
    weight = 3
    identifier = "media"
    url = "/media/"
[[menu.main]]
    name = "M2 Money Stock"
    pre = "<i class='fa fa-dollar-sign fa-fw'></i>"
    weight = 3
    identifier = "m2"
    url = "/m2/"
[social]

  github = "simulacra10"
  twitter = "wyeoakmobiledr"